### ISSUE TITLE
pandas.TimeSeries()

### ISSUE THREAD

**Issue by asinha94** [akloster/python-mindwave#7]
Im attempting to run the console.py example but get the following errors. 

```
Traceback (most recent call last):
  File "console.py", line 28, in <module>
    main()
  File "console.py", line 17, in main
    recorder = TimeSeriesRecorder()
  File "/usr/local/lib/python2.7/dist-packages/mindwave/parser.py", line 139, in __init__
    self.meditation = pd.TimeSeries()
AttributeError: 'module' object has no attribute 'TimeSeries'

```

I'm not too familiar with pandas but having looked through the API [here](http://pandas.pydata.org/pandas-docs/stable/api.html) I cannot find a TimeSeries. Are you using a developmental version?

Thanks in advance

**Comment by akloster** [comment]
Nope, I just haven't worked on this project for years. In older versions of Pandas there was a distinction between TimeSeries and Series objects. Now there is just the Series object, and if you give it a TimeIndex, it behaves the same as the TimeSeries index.

Later, I began developing "pysiology", which incorporates Muse and Mindwave, with its own parsers. It used an asyncio server and pushed the data to Jupyter Notebook. Currently I am working on integrating Muse support in a Kivy application, and I want to port it to Android.

I believe Kivy is the right framework for Neurofeedback with its strong support for completely custom GUIs. But somehow I always get stuck in developing the groundwork....

I also have yet another unfinished project which uses bcolz to record Timeseries like EEG and EKG efficiently in memory and on disk.

**Comment by iainmaoileoin** [comment]
Hi, I was planning to use this code.  Are you saying that it is getting close to too old to be useful and just going to be a minefield to download and get running?  If so, any suggestions where I should start for an Android/Unix type platform.  I dont want to spend my time working on low-level interfacing, but rather stand on the shoulders of other developers

**Comment by asinha94** [comment]
The core parser is still viable and I did end up using that heavly [here](https://github.com/asinha94/EEG_Controlled_Wheelchair/tree/master/eeg_reader). Apart from this pandas issue which was solved for me in this fork [here](https://github.com/robintibor/python-mindwave) which replaced pandas with plain old python lists, there is some dependency hassles to get though. If you want to do anything 'meaningful' with data you get out of the Mindwave you need to install NumPy and it's corresponsing version of SciPy (+ MKL) which for whatever reason started to compile from source on my machine and took close to 2 hours. I also had lots of issues with the default debian bluetooth stack (Bluez) which dropped A2DP from the core stack (I believed you can still utilize it through PulseAudio)

**Comment by iainmaoileoin** [comment]
Thanks.  I understand *some* of these issues.  I HAVE interfaced mindwave to my Ubuntu box using some of their dev tools, but it was hard work.  With some Xbox peripherals I have ended up using the Bluez stack.

Given your information I will press on, and expect a wee bit of fun!  Do you have any decent front-end code.  The low level interfaces are "easy for me", getting the pretty front-ends is the hard part.  I was hoping to use the front-end shown in the 'tube video leading to this link, but .....

**Comment by akloster** [comment]
The thing is that the byte stream parser works for a lot of different devices. There are mindwave headsets with bluetooth, which I recommend most heavily, but also one older model with a usb RF dongle, and then there is the actual thinkgear hardware module which speaks the same protocol over a serial line.

So, a lot of applications will depend on how you get at the data. For example, how do you actually access bluetooth, which is different for each kind of application. It's one way for pygame applications, another way for a websocket server, a kivy app on desktop and  then on android the Python bluetooth doesn't work at all and you'd have to bridge to Java.

That's why a decoupled parser implementation makes most sense in my view.
